# Generated by Django 5.1.4 on 2024-12-22 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=15, unique=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('mentor_image', models.ImageField(blank=True, null=True, upload_to='mentors/')),
                ('mentor_company', models.CharField(blank=True, max_length=255, null=True)),
                ('mentor_experience', models.PositiveIntegerField(default=0, help_text='Years of experience')),
                ('skills', models.CharField(blank=True, help_text='Comma-separated skills', max_length=500, null=True)),
                ('mentor_designation', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
